services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9999:80"
    volumes:
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - app1
      - app2
      - app3

  app1:
    image: rps-game
    #    ports:
    #      - "8081:8080"
    environment:
      JAVA_OPTS: "-DDEFAULT_BOUNDED_ELASTIC_ON_VIRTUAL_THREAD=true"

  app2:
    image: rps-game
    #    ports:
    #      - "8082:8080"
    environment:
      JAVA_OPTS: "-DDEFAULT_BOUNDED_ELASTIC_ON_VIRTUAL_THREAD=true"

  app3:
    image: rps-game
    #    ports:
    #      - "8083:8080"
    environment:
      JAVA_OPTS: "-DDEFAULT_BOUNDED_ELASTIC_ON_VIRTUAL_THREAD=true"

